### ISSUE TITLE
This should be updated. 

### ISSUE THREAD

**Issue by QPCrummer** [tr7zw/CraftFabric#8]
FukkitMC hasn’t been updated in 4 months. There isn’t really point of waiting. FukkitMC is dead. Clearly they have ran into a obstacle. Now is your chance to get your mod up and running!

**Comment by tr7zw** [comment]
Yea but to be fair, I don't want to get it up and running, since I don't have the time or incentive to do that. Found https://github.com/BukkitFabric/bukkit4fabric a few days ago, they are further than this project, more people, even try to support nms as good as possible, there is no reason for me to continue this project at this point.

**Comment by Jarfeh** [comment]
Isn't Bukkit much worse in terms of performance?
